### PR TITLE
Fix bug addstock and addprescription. Fix bugs in PED. Update DG.

### LINKED ISSUE #290: Fix Bug for addprescription
When adding prescription, if some medicine is expired the prescription goes through halfway

### PR DESCRIPTION
**Pull request by deonchung**
Fix #290 #289 #267 #256 #243 #235

### CODE REVIEW

File: src/main/java/utilities/parser/PrescriptionValidator.java [hunk 1]
```diff
@@ -173,4 +176,33 @@ public boolean isValidDate(Ui ui, String dateString) {
...
+            String expiryString = DateParser.dateToString(existingExpiry);
+            String prescribeDateString = DateParser.dateToString(prescribeDate);
+            boolean isNotExpired = (existingExpiry.after(prescribeDate) || prescribeDateString.equals(expiryString));
+
+            if (isSameMedicineName && !isDeleted && isNotExpired) {
+                existingQuantity += medicine.getQuantity();
+            }
+        }
+        return existingQuantity;
+    }
```
Comment (a-tph) [inline src/main/java/utilities/parser/PrescriptionValidator.java:206]: Perhaps can put this method in `PrescriptionManager` class instead since it is not exactly a validator.

File: src/main/java/command/order/DeleteOrderCommand.java [hunk 2]
```diff
@@ -59,20 +42,60 @@ public void execute() {
...
+            return true;
+        }
+
+        boolean isValidOrderId = orderValidator.isValidOrderId(ui, orderIdToDelete, medicines);
+
+        if (!isValidOrderId) {
+            logger.log(Level.WARNING, "Invalid order id is specified by user");
+            logger.log(Level.INFO, "Unsuccessful deletion of order");
+            return true;
+        }
```
Comment (a-tph) [inline src/main/java/command/order/DeleteOrderCommand.java:96]: Is this part necessary? should be caught in `containsInvalidParameters()` in line 81?

Comment (deonchung) [reply src/main/java/command/order/DeleteOrderCommand.java:96]: Required to check if the order id provided by user exists

**Review by a-tph — COMMENTED** [review]
LGTM
