### PR TITLE
Add sequence diagram to DG, modify UG and solve bug for deletedispense

### LINKED ISSUE #168: Add Sequence Diagram

### PR DESCRIPTION
**Pull request by deonchung**
Fix #168 

Add sequence diagram for addstock, adddispense, deletedispense and deleteorder 
Add  adddispense, deletedispense and deleteorder for userguide
Minor Changes to addstock, adddispense and deleteorder 
Solve bug in deletedispense

### CODE REVIEW

File: src/main/java/command/stock/AddStockCommand.java [hunk 1]
```diff
@@ -171,15 +171,17 @@ private boolean checkDateAndQuantity(Ui ui, ArrayList<Medicine> medicines, Strin
     private boolean checkValidParametersAndValues(Ui ui, LinkedHashMap<String, String> parameters,
                                                   ArrayList<Medicine> medicines, String[] requiredParameters,
                                                   String[] optionalParameters) {
-
-        if (CommandSyntax.containsInvalidParameters(ui, parameters, requiredParameters, optionalParameters,
-                CommandSyntax.ADD_STOCK_COMMAND, false)) {
+        boolean isInvalidParameters = CommandSyntax.containsInvalidParameters(ui, parameters, requiredParameters,
+                optionalParameters,
+                CommandSyntax.ADD_STOCK_COMMAND, false);
```
Comment (a-tph) [inline src/main/java/command/stock/AddStockCommand.java:176]: Perhaps can collapse into 1 line

File: src/main/java/command/dispense/DeleteDispenseCommand.java [hunk 2]
```diff
@@ -36,15 +36,19 @@ public void execute() {
         String[] requiredParameters = {CommandParameters.ID};
         String[] optionalParameters = {};
 
-        if (CommandSyntax.containsInvalidParameters(ui, parameters, requiredParameters, optionalParameters,
-                CommandSyntax.DELETE_DISPENSE_COMMAND, true)) {
+        boolean isInvalidParameter = CommandSyntax.containsInvalidParameters(ui, parameters, requiredParameters,
+                optionalParameters,
+                CommandSyntax.DELETE_DISPENSE_COMMAND, true);
```
Comment (a-tph) [inline src/main/java/command/dispense/DeleteDispenseCommand.java:41]: Perhaps can collapse into 1 line

**Review by a-tph — COMMENTED** [review]
LGTM
